#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

if ($argc === 1) {
    passthru('php bin/console', $returnVar);
    exit($returnVar);
}

$argument = $argv[1] ?? null;

if ($argument === 'test') {
    passthru('php bin/phpunit --colors=always', $returnVar);
    exit($returnVar);
}

echo "Unrecognized argument. Please use either 'test' or provide no argument to launch FizzBuzz in the console.\n";
exit(1);
