#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

if ($argc < 1) {
    echo "Please provide an argument (test or console).\n";
    exit(1);
}

$argument = $argv[1] ?? null;

if ($argument === null) {
    passthru('php bin/console', $returnVar);
    exit($returnVar);
}

if ($argument === 'test') {
    passthru('php bin/phpunit', $returnVar);
    exit($returnVar);
}

echo "Unrecognized argument.\nPlease use 'test' or no argument to lauch FizzBuzz in console'.\n";
exit(1);
