#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

if ($argc < 1) {
    echo "Please either provide the 'test' argument or no argument at all.\n";
    exit(1);
}

$argument = $argv[1] ?? null;

if ($argument === null) {
    passthru('php bin/console', $returnVar);
    exit($returnVar);
}

if ($argument === 'test') {
    passthru('php bin/phpunit --colors=always', $returnVar);
    exit($returnVar);
}

echo "Unrecognized argument. Please use either 'test' or provide no argument to launch FizzBuzz in the console.\n";
exit(1);
